name: mirrors_builder
description: Mirrors is a lightweight static reflection library for Dart, using code generation.
  It is designed as a modern alternative to `reflectable`.
version: 0.0.1
resolution: workspace
repository: https://github.com/alessandro-amos/mirrors.dart.git

environment:
  sdk: ">=3.8.2 <4.0.0"

# Add regular dependencies here.
dependencies:
  mirrors: ^0.0.1
  analyzer: ^8.0.0
  watcher: ^1.2.1
  path: ^1.9.1
  build_runner: ^2.10.5
  build: ^4.0.0
  dart_style: ^3.1.3

  glob: any
dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
