name: mirrors
description: A starting point for Dart libraries or applications.
version: 0.0.1
resolution: workspace
repository: https://github.com/alessandro-amos/mirrors.dart

environment:
  sdk: ">=3.8.2 <4.0.0"

# Add regular dependencies here.
dependencies:
  # path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
