name: test_mirror
description: A sample command-line application.
version: 0.0.1
publish_to: none
resolution: workspace
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.4

# Add regular dependencies here.
dependencies:
  mirror:
    path: ../mirror
  path: ^1.9.0

dev_dependencies:
  mirror_builder:
    path: ../mirror_builder
  lints: ^6.0.0
  test: ^1.25.6
